version: 2
registries:
  github:
    type: git
    url: https://github.com/Kilka-Software/
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_TOKEN }}

updates:
  - package-ecosystem: "pip"
    directory: "/"
    registries:
      - github
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "update dependabot-dep-poc : "
    labels:
      - "jrs-core"
    assignees:
      - "amazing-Mantse"
    reviewers:
      - "amazing-Mantse"
    allow:
      - dependency-name: "dependabot-dep-poc"


