name: Publish wiki
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [docs/**]
concurrency:
  group: wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Documentation Extras
        run: |
          pip install sphinx
          pip install sphinx-autobuild
          pip install sphinx-markdown-builder
      - name: Build the Docs
        run: | 
          sphinx-build -M markdown ./docs docs/_build/
      - uses: spenserblack/actions-wiki@v0.3.0
        with:
          path: docs/_build/markdown